
const data={
    productItems:[
        {
            id:'1',
            name:'Headphone',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'2',
            name:'Wifi modem',
            price:'1200rs',
            image:'logo192.png'
        },
        {
            id:'3',
            name:'USB drive',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'4',
            name:'Monitor',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'5',
            name:'Macbook',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'6',
            name:'iPad',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'7',
            name:'Fen',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'8',
            name:'AC',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'9',
            name:'Washing Machine',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'10',
            name:'Wall Watch',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'11',
            name:'Smart Watch',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'12',
            name:'Robot Car',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'13',
            name:'CPU',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'14',
            name:'Modem',
            price:'1200rs',
            image:'logo192.png'
        },
        {
            id:'15',
            name:'Scanner',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'16',
            name:'Keyboard',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'17',
            name:'Mouse',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'18',
            name:'Tablet',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'19',
            name:'Printer',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'20',
            name:'Camera',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'21',
            name:'iPhone',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'22',
            name:'Refrigerator',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'23',
            name:'Redio',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'24',
            name:'watch',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'23',
            name:'Computer',
            price:'1200rs',
            image:'logo192.png',
        },
        {
            id:'24',
            name:'Mobile',
            price:'1200rs',
            image:'logo192.png',
        }
    ]
}
export default data;

